-- POINT 1
CREATE DATABASE IF NOT EXISTS rossmary_corp;

-- POINT 2
CREATE TABLE IF NOT EXISTS products (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    unit VARCHAR(15),
    stock INT(5),
    price VARCHAR(10)
);

-- POINT 3
DESC products;